# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "playground"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Santiago Hernandez"]
  s.date = "2012-06-03"
  s.description = "Selenium Webdriver testing framework for web automation"
  s.email = "santi84@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "lib/page.rb",
    "lib/playground.rb",
    "lib/testcase.rb"
  ]
  s.homepage = "http://github.com/santius/playground"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.23"
  s.summary = "A ruby gem for using selenium webdriver"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

